// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag - run 'swag init' to regenerate
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "goTap Swagger Example API",
        "description": "Example API demonstrating Swagger/OpenAPI documentation with goTap framework",
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/api",
    "paths": {}
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/api",
	Title:       "goTap Swagger Example API",
	Description: "Example API demonstrating Swagger/OpenAPI documentation with goTap framework",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

func init() {
	swag.Register(swag.Name, &s{})
}

// Note: Run 'swag init -g main.go --output docs' to generate real documentation
